module.exports = {
    isCompactProcess () {
        return process.argv[2] === 'compacta';
    },
    
    isUncompactProcess () {
        return process.argv[2] === 'descompacta'
    },

    inputVerifications() {
        if (process.argv.length <= 4) {
            console.error('Use Example: node index.js (compacta|descompacta) ./folderToCompact ./nameOfFile.zip');
            process.exit(-1);
        }

        const typeFileToGenerate = process.argv[4].split('.')[1];

        if (typeFileToGenerate !== ('zip' || 'tar')) {
            console.error('Only .zip and .tar files are accepted to be generated by this program.');
            process.exit(-1);
        }
    }
}